PROJECT_CREATED = "project.created"
PROJECT_UPDATED = "project.updated"
PROJECT_ARCHIVED = "project.archived"
PROJECT_HARD_DELETED = "project.hard_deleted"
PROJECT_ACCESS_UPDATED = "project.access_updated"
PROJECT_MEMBER_ROLE_SET = "project.member_role_set"
PROJECT_MEMBER_REMOVED = "project.member_removed"
