# Domain events this module emits (06-Backend-Architecture.md §6.1/§6.6).
WORKSPACE_CREATED = "workspace.created"
WORKSPACE_UPDATED = "workspace.updated"
MEMBER_INVITED = "member.invited"
MEMBER_ROLE_CHANGED = "member.role_changed"
MEMBER_REMOVED = "member.removed"
# TDR-0056 joining, org chart and ownership.
MEMBER_PROFILE_UPDATED = "member.profile_updated"
MEMBER_JOINED_VIA_CODE = "member.joined_via_code"
MEMBER_JOIN_REQUESTED = "member.join_requested"
MEMBER_JOIN_APPROVED = "member.join_approved"
MEMBER_JOIN_REJECTED = "member.join_rejected"
MEMBER_LEFT = "member.left"
OWNERSHIP_TRANSFERRED = "workspace.ownership_transferred"
ROOM_CODE_CHANGED = "workspace.room_code_changed"
